print("Arithmetic operators")
num1=input("enter first number:")
num2=input("enter second number:")
num1=int(num1)
num2=int(num2)
print("addition:",num1+num2)
print("subtraction:",num1-num2)
print("multiplication:",num1*num2)
print("division:",num1/num2)
print("modules:",num1%num2)
print("exponent:",num1**num2)
print("floor division:",num1//num2)